### ISSUE TITLE
example fails

### ISSUE THREAD

**Issue by floswald** [alancrawford/Smolyak#2]
hi!

i'm getting stuck in the interpolations example with

``` julia
sg = SmolyakGrid(D,µ,Xlow,Xhigh)
ERROR: MethodError: `convert` has no method matching convert(::Type{Smolyak.SmolyakGrid}, ::Int64, ::Array{Int64,1}, ::Array{Float64,1}, ::Array{Float64,1})
This may have arisen from a call to the constructor Smolyak.SmolyakGrid(...),
since type constructors fall back to convert methods.
Closest candidates are:
  Smolyak.SmolyakGrid(::Union{Array{Int64,1},Int64}, ::Array{Float64,1}, ::Array{Float64,1})
  Smolyak.SmolyakGrid(::Union{Array{Int64,1},Int64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Int64)
  Smolyak.SmolyakGrid(::Union{Array{Int64,1},Int64}, ::Array{Int64,1})
  ...
 in call at essentials.jl:57

```

**Comment by alancrawford** [comment]
Did forking the most recent version help? I changed some of the syntax.

**Comment by floswald** [comment]
this fails on both branches for me, master and version3. On master, the error message is somewhat longer. :-)

**Comment by alancrawford** [comment]
Will take a look

**Comment by alancrawford** [comment]
OK, perhaps fork again from version3. I think should be fixed

**Comment by floswald** [comment]
``` julia
julia> include("Smolyak.jl")
WARNING: replacing module Smolyak
ERROR: LoadError: LoadError: UndefVarError: VecOrArray not defined
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/florian.oswald/git/SmolyakFork/src/smolgrid.jl, in expression starting on line 256
while loading /Users/florian.oswald/git/SmolyakFork/src/Smolyak.jl, in expression starting on line 44

```

in fact you call it `typealias VecOrAA{T} Union{Vector{T},AA{T}}` and not `VecOrArray`.

does this actually run for you? strange.

**Comment by alancrawford** [comment]
Works fine for me.

VecOrAA{T} does rule out a scalar case - is that the issue?

**Comment by floswald** [comment]
while loading /Users/florian.oswald/git/SmolyakFork/src/smolgrid.jl, in
expression starting on line 256

you say there is something like `VecOrArray`. you define this nowhere. you
only define `typealias VecOrAA{T} Union{Vector{T},AA{T}}` on line 41 of
Smolyak.jl.
that's the up to date version of branch version3.

do you want to update the master branch to this latest version at any point
by the way?
cheers

**Comment by alancrawford** [comment]
Good point on pushing to master. Once I get to bottom of this i will push version3 to master. 

So i am a bit confused. One of the changes i intended to make when moving to version3 was to omit the VecOrArray{T} types in favour of Vectors or Array of Arrays i.e. VecOrAA{T}. When I search my code files on version3 I can't find any reference to VecOrArray{T}, only to VecOrAA{T}. 

All of the typealiases i use are in lines 36 to 41 in Smolyak.jl:
typealias AA{T} Array{Array{T,1},1}
typealias AM{T} Array{Matrix{T},1}  
typealias AAA{T} Array{Array{Array{T,1},1},1}
typealias AAAA{T} Array{Array{Array{Array{T,1},1},1},1}
typealias ScalarOrVec{T} Union{T,Vector{T}}
typealias VecOrAA{T} Union{Vector{T},AA{T}}

**Comment by alancrawford** [comment]
typealias AA{T} Array{Array{T,1},1}
typealias AM{T} Array{Matrix{T},1}                                                                                 
typealias AAA{T} Array{Array{Array{T,1},1},1}
typealias AAAA{T} Array{Array{Array{Array{T,1},1},1},1}
typealias ScalarOrVec{T} Union{T,Vector{T}}
typealias VecOrAA{T} Union{Vector{T},AA{T}}

**Comment by floswald** [comment]
hmm, no idea why, but now it worked. i'm on a different machine though. will clean up the office mac tomorrow. thanks!
