### ISSUE TITLE
rename get_pinBFt! and getCoef!

### ISSUE THREAD

**Issue by floswald** [alancrawford/Smolyak#4]
hey,

i was confused by those function names. saying "get" means that you get something back. here is a suggestion. I realise you put the ! there, so that's ok, but I think it would be much clearer if you renamed those to

`make_pinBFt!` or `generate_pinBFt` or `fillin_pinBFt` etc. you are filling out a filed of the sp object here really.

**Comment by alancrawford** [comment]
No objection to that suggestion - perhaps i will change to make_pinBFt!
