### ISSUE TITLE
updateBasis!

### ISSUE THREAD

**Issue by floswald** [alancrawford/Smolyak#6]
I'm looking at your example. 

``` julia
sbX = SmolyakBasis(X,mu,Xlow,Xhigh,NumDeriv,NumDerivArgs)
makeBasis!(sbX)
```

so when I want to evaluate this basis repeatedly, but for always a different set of points `X`, but same bounds and all the rest, I have to go through this function right? if so, would it be possible to bypass a large junk of computation, by saying

``` julia
updateBasis!(sbX,newX)  #newX is a new set of points at which to evaluate the basis
```

**Comment by alancrawford** [comment]
Absolutely. For my purposes i wanted to separate these functions, but clearly a case for such a function.
